name: restaurant
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  android_alarm_manager: ^2.0.2  
  cached_network_image: ^3.1.0
  connectivity_plus: ^1.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^8.1.1+1
  flutter_remix: ^0.0.3
  get: ^4.3.4
  google_fonts: ^2.1.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14

flutter:
  uses-material-design: true
  assets:
    - assets/
